question_data = [
{"texto": "O sangue de uma lesma é verde.", "resposta": "True"},
{"texto": "O animal mais barulhento é o elefante africano.", "resposta": "False"},
{"texto": "Aproximadamente um quarto dos ossos humanos estão nos pés.", "resposta": "True"},
{"texto": "A área total da superfície de um pulmão humano é do tamanho de um campo de futebol.", "resposta": "True"},
{"texto": "Em West Virginia, EUA, se você acidentalmente atropelar um animal com seu carro, você pode levá-lo para casa para comer.", "resposta": "True"},
{"texto": "Em Londres, Reino Unido, se você morrer no Parlamento, tem direito a um funeral de estado.", "resposta": "Falso"},
{"texto": "É ilegal fazer xixi no oceano em Portugal.", "resposta": "True"},
{"texto": "Você pode conduzir uma vaca pelas escadas, mas não pelas escadas.", "resposta": "Falso"},
{"texto": "O nome original do Google era 'Backrub'.", "resposta": "True"},
{"texto": "O nome de solteira da mãe de Buzz Aldrin era 'Moon'.", "resposta": "True"},
{"texto": "Nenhum pedaço de papel seco quadrado pode ser dobrado ao meio mais de 7 vezes.", "resposta": "Falso"},
{"texto": "Alguns gramas de lata de chocolate para matar um cachorro pequeno.", "resposta": "True"},
{"texto": " O relâmpago é visto antes de ser ouvido porque a luz viaja mais rápido que o som.", "resposta": "True"},
{"texto": "A cidade do Vaticano é um país.", "resposta": "True"},
{"texto": " Melbourne é a capital da Austrália.", "resposta": "False"},
{"texto": " A penicilina foi descoberta no Vietnã para tratar a malária.", "resposta": "False"},
{"texto": " O Monte Fuji é a montanha mais alta do Japão.", "resposta": "True"},
{"texto": " Brócolis contém mais vitamina C do que limões ", "resposta": "True"},
{"texto": " As lâmpadas foram invenção de Thomas Edison.", "resposta": "False"},
{"texto": " A caixa preta em um avião é preta.", "resposta": "False"},
]